### ISSUE TITLE
Early warning BBC 

### ISSUE THREAD

**Issue by andk** [dagolden/Test-API#7]
Well, probably not early enough. #132252 has the details, DAGOLDEN/Test-API-0.008.tar.gz has started failing on bleadperl.

Unshortened link: https://rt.perl.org/Public/Bug/Display.html?id=132252

Diagnostics:

Not a GLOB reference at /tmp/loop_over_bdir-10385-cMEXnA/Test-API-0.008-0/blib/lib/Test/API.pm line 176.
t/02-public.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/11 subtests 
Not a GLOB reference at /tmp/loop_over_bdir-10385-cMEXnA/Test-API-0.008-0/blib/lib/Test/API.pm line 176.
t/03-export.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 8/14 subtests 
Not a GLOB reference at /tmp/loop_over_bdir-10385-cMEXnA/Test-API-0.008-0/blib/lib/Test/API.pm line 176.
t/04-class-ok.t ........ 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 3/5 subtests

**Comment by xdg** [comment]
Should be fixed now.
